last 122

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -26,6 +26,13 @@ jobs:
         run: |
           chmod +x gradlew
           ./gradlew build
+        continue-on-error: true  # 테스트 실패 시에도 빌드를 계속 진행
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: test-results
+          path: build/reports/tests/test  # 테스트 결과 업로드
       - name: Code vulnerability scanning
         uses: anchore/scan-action@v3
         id: scan
@@ -33,11 +40,11 @@ jobs:
           path: "${{ github.workspace }}"
           fail-build: false
           severity-cutoff: high
-#      - name: Upload vulnerability report
-#        uses: github/codeql-action/upload-sarif@v3
-#        if: success() || failure()
-#        with:
-#          sarif_file: ${{ steps.scan.outputs.sarif }}
+      #      - name: Upload vulnerability report
+      #        uses: github/codeql-action/upload-sarif@v3
+      #        if: success() || failure()
+      #        with:
+      #          sarif_file: ${{ steps.scan.outputs.sarif }}
       - name: Setup tools
         uses: alexellis/setup-arkade@v3
       - name: Install tools
@@ -47,6 +54,7 @@ jobs:
       - name: Validate Kubernetes manifests
         run: |
           kubeconform --strict k8s
+
   package:
     name: Package and Publish
     if: ${{ github.ref == 'refs/heads/main' }}
