fetch: commit-stage

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -16,17 +16,20 @@ jobs:
     steps:
       - name: Checkout source code
         uses: actions/checkout@v4
+
       - name: Set up JDK
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: 17
           cache: gradle
+
       - name: Build, unit tests and integration tests
         run: |
           chmod +x gradlew
           ./gradlew build
         continue-on-error: true  # 테스트 실패 시에도 빌드를 계속 진행
+
       - name: Code vulnerability scanning
         uses: anchore/scan-action@v3
         id: scan
@@ -34,21 +37,27 @@ jobs:
           path: "${{ github.workspace }}"
           fail-build: false
           severity-cutoff: high
-#      - name: Upload vulnerability report
-#        uses: github/codeql-action/upload-sarif@v3
-#        if: success() || failure()
-#        with:
-#          sarif_file: ${{ steps.scan.outputs.sarif }}
+
+      # SARIF 파일 업로드를 주석 처리
+      # - name: Upload vulnerability report
+      #   uses: github/codeql-action/upload-sarif@v3
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: ${{ steps.scan.outputs.sarif }}
+
       - name: Setup tools
         uses: alexellis/setup-arkade@v3
+
       - name: Install tools
         uses: alexellis/arkade-get@master
         with:
           kustomize: latest
           kubeconform: latest
+
       - name: Validate Kubernetes manifests
         run: |
           kustomize build k8s | kubeconform --strict -
+
   package:
     name: Package and Publish
     if: ${{ github.ref == 'refs/heads/main' }}
@@ -61,17 +70,20 @@ jobs:
     steps:
       - name: Checkout source code
         uses: actions/checkout@v4
+
       - name: Set up JDK
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: 17
           cache: gradle
+
       - name: Build container image
         run: |
           chmod +x gradlew
           ./gradlew bootBuildImage \
             --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+
       - name: OCI image vulnerability scanning
         uses: anchore/scan-action@v3
         id: scan
@@ -79,16 +91,20 @@ jobs:
           image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
           fail-build: false
           severity-cutoff: high
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
+
+      # SARIF 파일 업로드를 주석 처리
+      # - name: Upload vulnerability report
+      #   uses: github/codeql-action/upload-sarif@v3
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: ${{ steps.scan.outputs.sarif }}
+
       - name: Log into container registry
         uses: docker/login-action@v3
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Publish container image
         run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
